### ISSUE TITLE
Propose enhancement to Kill pid to Terminate app

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-xcuitest-driver#1385]
wda/apps/terminate

is not killing app completely. The app stays in background.

Facebook Idb / tidevice / gidevice has functionality to kill app which also removes from background apps.(finding PID of app processes and killing app process by pid.

Possible to add this enhancement to Webdriveragent.

**Comment by KazuCocoa** [comment]
Added killing a pid via instruments service in https://github.com/appium/appium-xcuitest-driver/pull/1386 .

In my device's some apps could be killed with terminateApp (via XCTest's terminate) and the instruments service's killApp as the same (I mean both case had no pid via `installedApplicationsMatching:registerUpdateToken:` by instruments service after calling them), so it would be helpful to check such killing pid via instruments service is expected behavior for you.
