### ISSUE TITLE
Enable support for toggle network capabilities

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium-xcuitest-driver#2485]
Similar to Android where the user can disable the phone from the network, it would be nice if similar things are possible on iOS. I know that iOS has limitations when it comes to automating the device and according to [some threads](https://www.reddit.com/r/iOSProgramming/comments/zewge2/disable_network_for_simulator/) this is not even possible natively but maybe we can use some sort of proxy.

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-enableconditioninducer is currently what we could offer right now to emulate network conditions.

Btw, in iOS real devices, when network condition changes, the xctest session could end (this is OS's behavior.) Then, WDA process could end. So probably, it's not possible to change the network connection state on/off during automation in the current condition on current iOS behavior. Old era kept working when I tested it out via UI interaction, but this behavior started since some iOS version. I haven't checked recent OS versions but communion between real devices and the host machine is over network technical stack so I guess not possible yet.

**Comment by christian-bromann** [comment]
Thanks @KazuCocoa for this information. I will go ahead and close this then. I wasn't aware that iOS is __that__ restricted.
