### ISSUE TITLE
Swipe not working correctly with Appium 1.6.0 in iOS

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium-xcuitest-driver#275]
Hi @imurchie and @jlipps ,
What ever the start and end X and Y offsets, swipe() is doing operation from left to right. I tried the below two scenarios, in both scenario appium trying to swipe screen from left to right. 

`driver.swipe(300, 250, 90, 250, 500); 
`
`driver.swipe(90, 250, 300, 250, 500);`

Is this known issue or I am doing anything wrong?

**Comment by alexanderustwo** [comment]
We're seeing similar issues in our tests. We're trying to drag up a view element from the lower part of the screen. This used to work with the UIAutomation driver.

swipe(:start_x => 251, :start_y => 450, :end_x => 280, :end_y => 100, :touchCount => 1, :duration => 1000)

**Comment by imurchie** [comment]
Can either of you provide some logs of what is happening on the server?

**Comment by vikaspune** [comment]
Can we have any sample application like "Paint brush" or something to check the swipe ( touches / drag and drop) is properly happening on UI line drawing? Please share the sample project if there is any, I would like to test Appium 1.6 and all upcoming releases with swipe.

I also have faced swipe issue many times with Appim 1.4, appium 1.5 and appium 1.6.
According to my ovservation appium 1.4 was using start and end points as absolute pints ( e.g. startx, starty, endx, endy)

Then in Appium 1.5 there was a change, end point made relative to start point. (e.g. startx, starty, offsetX,offsetY) offset can be +ve or -ve numbers

But recently i checked Appium 1.6 it is now using points similar to appium 1.4. that is absolute start and end points instead of offsets.

Also I did noticed the time duration value is changed. like on Appium 1.4 we called driver.swipe() with time in mili seconds ( e.g. 1000 for 1 seconds) but in Appium1.6 driver.swipe() is now taking seconds as duration not miliseconds. 

I have observed this with Appium Java client 4.1.2 (for Appium 1.6) I am not sure about other bindings.

@shivakrishnach31 Can you please change the last param value like 
```  
driver.swipe(300, 250, 90, 250, 1);
driver.swipe(90, 250, 300, 250, 1);
```

**Comment by alexanderustwo** [comment]
@imurchie

I'm not very familiar with Appium in general. I've just been looking into getting our existing test suite to run with the latest versions of iOS (and thus did the change to use XCUITest etc).

Could you please provide some additional info on where I can get the correct logs? Do I need to set any specific flags to get verbose logs?

**Comment by shivakrishnach31** [comment]
@imurchie , please find the below log

> [HTTP] <-- POST /wd/hub/session/91789c1c-e6f1-4549-9af0-5ab7a7266108/elements 200 1442 ms - 74 
> [HTTP] --> POST /wd/hub/session/91789c1c-e6f1-4549-9af0-5ab7a7266108/touch/perform {"actions":[{"action":"press","options":{"x":300,"y":250}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":90,"y":250}},{"action":"release","options":{}}]}
> [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
> [debug] [XCUITest] Executing command 'performTouch'
> [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/6A693013-566F-47DE-85D2-54C980847BAD/uiaTarget/0/dragfromtoforduration] with body: {"fromX":300,"fromY":250,"t...
> [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"6A...
> [MJSONWP] Responding to client with driver.performTouch() result: {}
> [HTTP] <-- POST /wd/hub/session/91789c1c-e6f1-4549-9af0-5ab7a7266108/touch/perform 200 3470 ms - 74 
> [HTTP] --> POST /wd/hub/session/91789c1c-e6f1-4549-9af0-5ab7a7266108/elements {"using":"accessibility id","value":"iPad"}

**Comment by shivakrishnach31** [comment]
I tried with latest Appium Java Client 4.1.2-2 and used IOSDriver instead of AppiumDriver for driver initialization. Now swipe is working as expected.

**Comment by alexanderustwo** [comment]
@shivakrishnach31
Would you mind sharing a bit more information on exactly how you changed to use the IOSDriver instead of the AppiumDriver?

We're also facing swipe issues, but as I'm quite new to Appium I'm not sure how the thing you described is done. Would love to try to make the same change (if possible) on our setup, and see if that resolves our problem as well.

**Comment by vikaspune** [comment]
Alexander, Just try using AppiumDriver<MobileElement>driver = new
IOSDriver(url,caps);

**Comment by estellemasso** [comment]
Swiping from bottom to the top and from right to left do not work at all with python client. However, swiping from top to bottom and left to right work fine. What could be the reason? I am using TouchAction too and the behavior is the same.
