### ISSUE TITLE
TODO: Implement support for WebDriverAgent deactivateApp 

### ISSUE THREAD

**Issue by kaleposhobios** [appium/appium-xcuitest-driver#3]
Creating this issue so I can work on it. 

What I want to do is add support for sending the WebDriverAgent the deactivateApp command. As far as I can tell, it's not supported now.

Please comment if this is a misguided goal.

**Comment by kaleposhobios** [comment]
Hi anyone,

I started doing this (worst case at least I learn more about the projects). What I did so far was:
1. Added /appium/ to driver.js getProxyAvoidList, because any appium command would have to be modified before sent to WebDriver
2. Added new command "closeApp". (Maybe there's another command that would be better suited but I used this for now).
3. I implemented that method as per the below code:
```javascript
commands.closeApp = async function () {
  try {
    let nativeDriver = await this.getNativeDriver();
    //Deactivate app is sent to WebDriverAgent via POST to 'deactivateApp'
    await request({

          url: url.format(nativeDriver.url) + 'deactivateApp',
          method: 'POST',
          resolveWithFullResponse: true
        })
        .then(function (response) {
          // Deactivate succeeded...
          logger.info(`Successfully deactivated the app. Response: ${response}`);
        })
        .catch(function (err) {
          // Deactivate failed...
          logger.warn(`Something went wrong whilst deactivating the app: ${err}`);
        });

  } catch (err) {
    logger.warn(`Something went wrong whilst deactivating the app: ${err}`);
    throw err;
  }
};
```

But, it's not working. I suspect I'm not POSTING to WebDriverAgent correctly. Since the existing code is just proxying, I guess perhaps that's why I can't figure it out? 

I'm hopeful someone can shine a light for me on the proper way to intercept (if I'm doing that part incorrectly) and then transform or pass the method to WebDriverAgent.

Perhaps what I should actually be doing is simply, intercepting the call like I am, but then modifying the endpoint and then simply giving it to the proxy again?

**Comment by cnejame** [comment]
I'm guessing here, but I think the intention of the `driver.close_app()` function is to terminate the app, not to just suspend it, like pressing the Home button would do.

I think the function you'll eventually be looking to call with `driver.close_app()` is this one:

http://masilotti.com/xctest-documentation/Classes/XCUIApplication.html#//api/name/terminate

I don't see any existing endpoint that just calls that, though. But I do see it used in `FBXCTSession.m`, and it looks like you'd call it from within a `FBRouteCommandHandler`'s `route` method like this:

```obj-c
+ (NSArray *)routes
{
    return
    @[
      [[FBRoute POST:@"/endpoint"] respond: ^ id<FBResponsePayload> (FBRouteRequest *request) {
          [request.session.application terminate];
          return FBResponseDictionaryWithOK();
      }],
      ];
}
```

I'm messing with it now to see if I can get it to work, but no luck yet.

**Comment by cnejame** [comment]
Welp, I was close. I was looking at the wrong class though.

Turns out, you have to import `"FBXCTSession.h"`, and then have something in the `routes` method like this:

```obj-c
+ (NSArray *)routes
{
    return
    @[
        [[FBRoute POST:@"/endpoint"] respond: ^ id<FBResponsePayload> (FBRouteRequest *request {
            FBXCTSession *session = (FBXCTSession *)request.session;
            [session.application terminate];
            return FBResponseDictionaryWithOK();
        }],
    ];
}

**Comment by kaleposhobios** [comment]
Hey,

Thanks for looking into this. You are right, and I actually switched up my
command to the appium command "deactivate". I routed this command through
to the WebDriverAgent and it worked!

You can find my commit in my "appium commands" branch of the appium
xctsuite in Truveris. The only other thing you have to do is update the git
submodule for WebDriverAgent from appium/WebDriverAgent to
truveris/WebDriverAgent

Then run git submodule sync.

Then you can actually run matt_test.py and it will work!!

**Comment by cnejame** [comment]
It does background the app, but it doesn't return it to the foreground. I'm still looking at your changes, but I take it you're calling the UIAutomation method `deactivateAppForDuration`? If so, that would explain why, as that method hasn't worked for a while. Here's a link for reference:

https://forums.developer.apple.com/thread/19047

I do think that we can do it with XCTest stuff though, but it would likely require making a new endpoint in the `XCTWebDriverAgentLib` to make a combination of method calls to get this working.

I'm thinking that we can just press the Home button via:
```obj-c
[[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];
```
then sleep for the desired duration, then quickly press the Home button twice and tap the app. 

It's not a built-in function, like `deactivateAppForDuration`, but it would theoretically do exactly what a user would do to put the app in the background and then resume it.

Loading up the Appium inspector and pressing the Home button twice in the simulator (CMD + Shift + H) shows a `UIAWindow` named "SBSwitcherWindow", that has a `UIAScrollView` inside it named "AppSwitcherScrollView". The view for suspended app is shown here as a generic `UIAElement`, with the app's name as the name of the element. That hopefully means we can jump through that hierarchy to tap it, but we'd have to make sure we do, because in this view, the icon for the app that's placed on the Home view can also be referenced by name, although it's listed as a `UIAButton`.

**Comment by kaleposhobios** [comment]
For the resume app, we will indeed have to implement a way to resume the app. Whatever xcuitest supports best, we can do. Like you say, maybe the best is just to double-tap the home button the find the app and tap it to resume.
