### ISSUE TITLE
is it possible to run directly xctest on ipa or app file through terminal? 

### ISSUE THREAD

**Issue by pixyish** [appium/appium-xcuitest-driver#309]
Hi,

we have executed xctest through terminal by following command

xcodebuild test -project $project_Path -scheme $Scheme_name -destination 'platform=iOS,id=$UDID'

is it possible to run xctest through appium without using project path or source code

**Comment by imurchie** [comment]
I'm not sure what you mean. Appium uses an internal project and source for the test.

**Comment by pixyish** [comment]
Hi @imurchie 

Apology that i had not made my point clear, So basically as per my project requirment i need to run test automation in an iOS10 Device through command line tool.

As of now using xcodebuild test command i can run the Automation on iOS 10 Device, however this xcodebuild test command requires the Application source code path (xcodebuild test -project $project_Path ) to run XCUITest.

Now my question is how can i run automation using appium in iOS 10. If you can point me to the specific set of appium 1.6.0 command, that will help.

**Comment by imurchie** [comment]
You do not need the source code of your application to test through Appium, you just need a developer signed version of the app (as .app or .ipa). You need to specify the `app` desired capability, and the appropriate configuration in order to build the automation system.

The details are here: https://github.com/appium/appium-xcuitest-driver#real-devices

For general appium usage, you can direct questions to https://discuss.appium.io/ as well as read the documentation at https://appium.io/
