### ISSUE TITLE
Handle WebDriverAgent /uiaelement/ routes

### ISSUE THREAD

**Issue by kaleposhobios** [appium/appium-xcuitest-driver#7]
Webdriveragent supports many nice new XCUITest behaviors like scrolling with the /uiaElement/:id/value route convention. An example of this is pickers:

In the former iOS driver we were handling sending commands to pickers as follows:
   dob_field = self.driver.find_element_by_name("form_dob_field")
   dob_field.send_keys(["February", "17", "1986"])

In this new driver, that sends the following command to webdriveragent:
    POST ...element/31/value

However, based on webdriveragent code, they do support pickers directly, but they expect the following route:
    [[FBRoute POST:@"/uiaElement/:id/value"]

Webdriveragent also supports many other nice new XCUITest behaviors like scrolling with this same route convention.

I'm not positive exactly where /uiaElement/ comes from. I'm thinking it's an "extension" they added to extend the Selenium spec to support these additional commands.

My question / issue is, how to best support this in Appium? My initial answer is, to leverage the "mobile: " commands the same way those used to be used, and any time there is "mobile: " in front, to hit the /uiaElement/ endpoint instead of /element/ endpoint. 

What does everyone think?

**Comment by Jonahss** [comment]
So, we already decided that the old "mobile: " commands were kind of a mistake that we don't want to repeat. @jlipps and I were brainstorming about how to handle developers that want to add custom routes to drivers.

At a first glance, we would like to have all the routes organized in https://github.com/appium/node-mobile-json-wire-protocol  the JSON wire protocol was built to be extensible, so adding `/uiaElement` routes is just fine.

We were also thinking about a way to implement a custom route outside of the mjsonwp repo, so that "unofficial" routes don't need to be merged into this shared repo.

@jlipps @imurchie discuss?

**Comment by kaleposhobios** [comment]
@Jonahss that makes sense, thanks. Can someone confirm that I'm even understanding the situation correctly? I.e. that WebDriverAgent adds the /uiaElement for the reasons I'm thinking? And, what approach we'd want to take to support it? That is, I'd certainly like to add direct support for pickers. And since WDA already has the /uiaElement route for this, I was thinking that it would be inside appium-xcuitest is where we'd want to handle it. 

But, maybe this isn't the case. In WDA's /element/:id/value route, it could just check if it's a picker, and then if so, use the XCTest picker command. I can't think of a reason why there would ever be a need to send a key command to a picker (which is what it does now).

**Comment by Jonahss** [comment]
Exactly, your suggestion of automatically detecting the element type could be the preferred way to go.

If the facebook devs don't want to add that automatic functionality, we could have the appium driver do the rerouting, turning /element/:id/value -> /uiaelement/:id/value

We can ask @mmmulani about the reasoning for the routing scheme. I know they're open to adding routes to webdriveragent in order to be more compliant with the spec.

**Comment by jlipps** [comment]
By far the best solution is just to have WDA use the correct spec. @mmmulani are you open to that?

**Comment by mmmulani** [comment]
yea definitely

**Comment by kaleposhobios** [comment]
Just to confirm...what would the "correct spec" be with regards to /uiaelement? What is meant is, just having it be /element and auto-detecting the correct action to take based on element type?

**Comment by jlipps** [comment]
@kaleposhobios yeah that's my opinion. knowing how to set an element's value should be an internal decision by the framework; it can just expose the regular POST /element/:id/value api

**Comment by Jonahss** [comment]
:+1:
